package assistant

import (
	"context"
	"github.com/sashabaranov/go-openai"
)

const PROMPT = `
You are a helpful assistant that helps reading infrastructure changes from JSON objects generated by terraform. 
You must follow below rules:
- Provide a clear and accurate summary of the changes
- Highlight the key actions 
- Avoid technical jargon where possible
- Focus on what will change, why it matters, and any potential impacts
- Output must be include Key Actions, Potential Impacts and Why These Changes Matter
- Markdown headings must start from H1
- Be precise and clear
`

type Service interface {
	Assist(input string) (string, error)
}

type service struct {
	client *openai.Client
}

var _ Service = &service{}

func New(token string) *service {
	client := openai.NewClient(token)
	return &service{client: client}

}

func (s service) Assist(input string) (string, error) {
	resp, err := s.client.CreateChatCompletion(
		context.Background(),
		openai.ChatCompletionRequest{
			Model: openai.GPT4o,
			Messages: []openai.ChatCompletionMessage{
				{
					Role:    openai.ChatMessageRoleSystem,
					Content: PROMPT,
				},
				{
					Role:    openai.ChatMessageRoleUser,
					Content: input,
				},
			},
		},
	)

	if err != nil {
		return "", err
	}
	return resp.Choices[0].Message.Content, nil

}
